version: '3.9'

services:
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app_network

  locust:
    image: python:3.10
    volumes:
      - .:/app
    working_dir: /app
    command: ["./wait-for-it.sh", "web:8000", "--", "sh", "-c", "pip install -r requirements.txt && locust -f locust/locustfile.py --host=http://web:8000"]
    ports:
      - "8089:8089"
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge